version: '3.8'

services:
  etl:
    image: cryptoloader:latest
    hostname: etl-firstattempt
    container_name: etl-firstattempt
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - etl_data:/glustervol1
      - /home/ubuntu/.ssh:/home/appuser/.ssh:ro
    environment:
      - HADOOP_CONF_DIR=/opt/spark//conf
      - YARN_CONF_DIR=/opt/spark/conf
    networks:
      - crypto-network
      - spark-hadoop_cluster-network


volumes:
  etl_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/glusterfs

networks:
  crypto-network:
    external: true
  spark-hadoop_cluster-network:
    external: true
