version: '3.8'

services:
  etl:
    image: cryptoloader:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - etl_data:/glustervol1
    networks:
      - crypto-network
      - spark-hadoop_cluster-network


volumes:
  etl_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/glusterfs

networks:
  crypto-network:
    external: true
  spark-hadoop_cluster-network:
    external: true
